language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO_VERSION=1.8.19 MODULE=multi_email_field.tests
  - DJANGO_VERSION=1.9.13 MODULE=multi_email_field.tests
  - DJANGO_VERSION=1.10.8 MODULE=multi_email_field.tests
  - DJANGO_VERSION=1.11.28 MODULE=multi_email_field.tests
  - DJANGO_VERSION=2.2.10 MODULE=multi_email_field.tests
  - DJANGO_VERSION=3.0.3 MODULE=multi_email_field.tests

install:
  - pip install six pyquery
  - pip install -q Django==$DJANGO_VERSION
  - pip install coverage

script: coverage run quicktest.py $MODULE

after_success:
 - pip install coveralls
 - coveralls

# We need to exclude old versions of Python for tests with Django >= 2
matrix:
    exclude:
        - python: 2.7
          env: DJANGO_VERSION=2.2.10 MODULE=multi_email_field.tests
        - python: 2.7
          env: DJANGO_VERSION=3.0.3 MODULE=multi_email_field.tests
        - python: 3.5
          env: DJANGO_VERSION=3.0.3 MODULE=multi_email_field.tests
